<?php

namespace EloBoostBundle\Repository;

/**
 * RPPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RPPurchaseRepository extends \Doctrine\ORM\EntityRepository
{
    public function NotRedeemedRP(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT count(RP) FROM EloBoostBundle:RPPurchase RP WHERE RP.redeemedAt is NULL AND RP.transaction is not null');
        return $query->getResult();
    }
    public function PaidbutnotredemmedRP(){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT count(RP) FROM EloBoostBundle:RPPurchase RP WHERE (RP.redeemedAt is NULL) AND TRUE = (SELECT(P.status) FROM EloBoostBundle:Payment P WHERE P.RP = RP.id) ');
        return $query->getResult();
    }

    public function countall(){
        return $this->getEntityManager()
            ->createQuery("SELECT COUNT (RP) FROM EloBoostBundle:RPPurchase RP") ->getOneOrNullResult();
    }

    public function countpaid(){
        return $this->getEntityManager()
            ->createQuery("SELECT count(P) FROM EloBoostBundle:Payment P WHERE P.status = true AND P.RP is NOT NULL")->getOneOrNullResult();
    }
}
